CREATE USER IF NOT EXISTS 'kds'@'localhost' IDENTIFIED BY 'kds@123';
CREATE USER IF NOT EXISTS 'kds'@'127.0.0.1' IDENTIFIED BY 'kds@123';

CREATE DATABASE IF NOT EXISTS kds_app
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON kds_app.* TO 'kds'@'localhost';
GRANT ALL PRIVILEGES ON kds_app.* TO 'kds'@'127.0.0.1';

FLUSH PRIVILEGES;
